apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: k8s-demo-cluster
  region: us-west-2

nodeGroups:
  - name: ng-1
    instanceType: t3.small
    desiredCapacity: 1
  - name: ng-2
    instanceType: t3.small
    desiredCapacity: 1
